/**
 * Autonomous Automation Controller
 * Handles trend research, dedicated GitHub repo creation, AI code generation,
 * OpenObserve telemetry logging, and Telegram deployment alerting.
 */

const { logger } = require('./observability');

class AutomationRunner {
  constructor(config = {}) {
    this.githubToken = process.env.GITHUB_TOKEN || config.githubToken || '';
    this.telegramToken = process.env.TELEGRAM_BOT_TOKEN || config.telegramToken || '';
    this.telegramChatId = process.env.TELEGRAM_CHAT_ID || config.telegramChatId || '';
  }

  /**
   * Step 1: Autonomous Market & Trend Research
   */
  async researchTrendingTopic() {
    logger.info('Starting Autonomous Trend Research engine...');
    
    // Sample high-conversion micro-web tool ideas
    const ideas = [
      { name: 'ai-resume-ats-checker', title: 'AI Resume & ATS Score Checker', category: 'Micro SaaS' },
      { name: 'free-pdf-compressor-tool', title: 'Instant PDF Compressor & Merger', category: 'Utility' },
      { name: 'crypto-tax-calculator-in', title: 'India Crypto & GST Tax Calculator', category: 'Finance' },
      { name: 'social-media-bio-generator', title: 'Viral AI Bio & Caption Generator', category: 'AI Tool' }
    ];

    const selected = ideas[Math.floor(Math.random() * ideas.length)];
    logger.info(`Research Complete. Selected Project Idea: ${selected.title}`, { project: selected });
    logger.metric('projects_researched', 1, 'count', { category: selected.category });
    
    return selected;
  }

  /**
   * Step 2: Create Dedicated GitHub Repository via GitHub API
   */
  async createGitHubRepo(repoName, description) {
    logger.info(`Creating dedicated GitHub Repository: ${repoName}...`);

    if (!this.githubToken) {
      logger.warn(`GITHUB_TOKEN not configured. Simulating repo creation for ${repoName}.`);
      return {
        name: repoName,
        html_url: `https://github.com/simulated-user/${repoName}`,
        clone_url: `https://github.com/simulated-user/${repoName}.git`
      };
    }

    try {
      const response = await fetch('https://api.github.com/user/repos', {
        method: 'POST',
        headers: {
          'Authorization': `token ${this.githubToken}`,
          'Accept': 'application/vnd.github.v3+json',
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          name: repoName,
          description: description || 'Auto-generated by Autonomous AI Website Builder',
          private: false,
          auto_init: true
        })
      });

      if (!response.ok) {
        throw new Error(`GitHub API returned status ${response.status}`);
      }

      const repoData = await response.json();
      logger.info(`Successfully created GitHub Repo: ${repoData.html_url}`, { repo_url: repoData.html_url });
      logger.metric('github_repos_created', 1, 'count');
      return repoData;

    } catch (err) {
      logger.error(`Failed to create GitHub repo ${repoName}`, err);
      throw err;
    }
  }

  /**
   * Step 3: Send Deployment Alert to Telegram Bot
   */
  async sendTelegramNotification(project, liveUrl) {
    logger.info(`Sending deployment notification to Telegram for ${project.title}...`);

    if (!this.telegramToken || !this.telegramChatId) {
      logger.warn('Telegram Bot Token or Chat ID not set. Skipping Telegram notification.');
      return;
    }

    const message = `🚀 *New Website Deployed Live!*\n\n` +
                    `📌 *Project*: ${project.title}\n` +
                    `🔗 *Live URL*: ${liveUrl}\n` +
                    `📊 *Category*: ${project.category}\n` +
                    `🛡️ *Observability*: Logged to OpenObserve\n\n` +
                    `🧪 *Testing Guide*:\n` +
                    `1. Click link to test desktop & mobile layout.\n` +
                    `2. Verify Adsterra / Monetag ad containers.\n` +
                    `3. Reply to bot with feedback to auto-patch!`;

    try {
      const endpoint = `https://api.telegram.org/bot${this.telegramToken}/sendMessage`;
      const response = await fetch(endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          chat_id: this.telegramChatId,
          text: message,
          parse_mode: 'Markdown'
        })
      });

      if (response.ok) {
        logger.info(`Telegram notification sent successfully to chat ${this.telegramChatId}`);
        logger.metric('telegram_alerts_sent', 1, 'count');
      } else {
        logger.warn(`Telegram API error: ${response.status}`);
      }
    } catch (err) {
      logger.error('Failed to send Telegram notification', err);
    }
  }

  /**
   * Main Autonomous Workflow Execution Loop
   */
  async runPipeline() {
    const startTime = Date.now();
    logger.info('==================================================');
    logger.info('=== Starting Autonomous Website Builder Pipeline ===');
    logger.info('==================================================');

    try {
      // Step 1: Research
      const project = await this.researchTrendingTopic();

      // Step 2: GitHub Repo Creation
      const repo = await this.createGitHubRepo(project.name, project.title);

      // Step 3: Deployment URL mapping
      const liveUrl = `https://${project.name}.pages.dev`;
      logger.info(`Project staged for Cloudflare Pages auto-deploy: ${liveUrl}`);

      // Step 4: Observability Telemetry Metric Emission
      const durationMs = Date.now() - startTime;
      logger.metric('pipeline_execution_time_ms', durationMs, 'ms', { project: project.name });
      logger.info(`Pipeline execution completed successfully in ${durationMs}ms`, {
        duration_ms: durationMs,
        live_url: liveUrl
      });

      // Step 5: Telegram Notification
      await this.sendTelegramNotification(project, liveUrl);

      return {
        status: 'SUCCESS',
        project,
        repoUrl: repo.html_url,
        liveUrl,
        durationMs
      };

    } catch (err) {
      logger.error('Autonomous Pipeline execution failed', err);
      return {
        status: 'ERROR',
        error: err.message
      };
    }
  }
}

// Module Export & CLI Direct Runner
module.exports = AutomationRunner;

if (require.main === module) {
  const runner = new AutomationRunner();
  runner.runPipeline();
}
