/**
 * Paperclip Agent - Documentation & Orchestration Only
 * 
 * This agent NO LONGER handles code generation or testing.
 * All coding/testing is performed EXCLUSIVELY by OpenCode and Kilo agents.
 * 
 * Paperclip is retained ONLY for:
 * - Non-coding documentation orchestration (if needed)
 * - Background service coordination
 * 
 * All template generation has been removed per project constraints.
 */

const { logger } = require('./observability');

class PaperclipAgent {
  constructor() {
    logger.info('📋 [Paperclip Agent] Initialized in documentation-only mode. Code generation and testing disabled.');
  }

  /**
   * Generate documentation placeholders via agent prompts.
   * Actual content is generated by OpenCode/Kilo agents in autonomous_engine.js
   */
  async generateDocumentation(projectName, agentName = 'OpenCode') {
    logger.info(`📋 [Paperclip Agent] Documentation generation delegated to ${agentName} agent.`);
    return {
      architecture: null,
      readme: null,
      sitemap: null,
      robots: null
    };
  }

  /**
   * QA testing is handled EXCLUSIVELY by KiloAgent.runTests()
   * This method is kept as a stub for backward compatibility only.
   */
  runTests(html) {
    logger.warn('⚠️ [Paperclip Agent] runTests() is DEPRECATED. Use KiloAgent.runTests() instead.');
    return {
      htmlSyntax: false,
      jsSyntax: false,
      adSlots: false,
      seoSchema: false,
      mobileResponsive: false,
      passed: false,
      errors: ['PaperclipAgent.runTests() is deprecated. Use KiloAgent.runTests() instead.']
    };
  }

  /**
   * Project building is handled EXCLUSIVELY by OpenCode and Kilo agents
   * This method is kept as a stub for backward compatibility only.
   */
  async buildProject(project) {
    logger.warn('⚠️ [Paperclip Agent] buildProject() is DEPRECATED. Use MasterAutonomousEngine.executeFullRun() instead.');
    return {
      html: '<!DOCTYPE html><html><head><title>Deprecated</title></head><body><h1>PaperclipAgent.buildProject() is deprecated.</h1></body></html>',
      architecture: null,
      readme: null,
      sitemap: null,
      robots: null,
      testResults: {
        htmlSyntax: false,
        jsSyntax: false,
        adSlots: false,
        seoSchema: false,
        mobileResponsive: false,
        passed: false,
        errors: ['PaperclipAgent.buildProject() is deprecated.']
      }
    };
  }
}

module.exports = PaperclipAgent;
